FROM openjdk:13-jdk-alpine

COPY EPM-configuration/build/libs/EPM-configuration-0.0.1-SNAPSHOT.jar EPM-configuration-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/EPM-configuration-0.0.1-SNAPSHOT.jar"]